name: Build on Commit

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v3.1.0

