name: Build on Commit

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build Jekyll for GitHub Pages
      uses: actions/jekyll-build-pages@v1.0.8
    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v2.0.3



